spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/chibbo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true